// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsKbpvTUhjmOu2G9IN6nFb9D1m7nnEyG4',
    appId: '1:3019565963:web:77c64f23cdf8171535dd8e',
    messagingSenderId: '3019565963',
    projectId: 'toonarchive-c3859',
    authDomain: 'toonarchive-c3859.firebaseapp.com',
    storageBucket: 'toonarchive-c3859.firebasestorage.app',
    measurementId: 'G-LPB2Y1CCB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4I7ZGyOX1CnDj2NxXK9ReQV_jhPQErIs',
    appId: '1:3019565963:android:f499a70fe618dcb435dd8e',
    messagingSenderId: '3019565963',
    projectId: 'toonarchive-c3859',
    storageBucket: 'toonarchive-c3859.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxx4qqtTnlAQNxMCCaXPNTnmNMSxTYjKY',
    appId: '1:3019565963:ios:39f305655c8e99a835dd8e',
    messagingSenderId: '3019565963',
    projectId: 'toonarchive-c3859',
    storageBucket: 'toonarchive-c3859.firebasestorage.app',
    androidClientId: '3019565963-ej71296teij3hjl9scrjdeqcsc2m3bom.apps.googleusercontent.com',
    iosClientId: '3019565963-g79mur7hj046ttu34i1acmaqjheif1mb.apps.googleusercontent.com',
    iosBundleId: 'com.example.toonarchive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxx4qqtTnlAQNxMCCaXPNTnmNMSxTYjKY',
    appId: '1:3019565963:ios:39f305655c8e99a835dd8e',
    messagingSenderId: '3019565963',
    projectId: 'toonarchive-c3859',
    storageBucket: 'toonarchive-c3859.firebasestorage.app',
    androidClientId: '3019565963-ej71296teij3hjl9scrjdeqcsc2m3bom.apps.googleusercontent.com',
    iosClientId: '3019565963-g79mur7hj046ttu34i1acmaqjheif1mb.apps.googleusercontent.com',
    iosBundleId: 'com.example.toonarchive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsKbpvTUhjmOu2G9IN6nFb9D1m7nnEyG4',
    appId: '1:3019565963:web:c2d1d059e18e08a635dd8e',
    messagingSenderId: '3019565963',
    projectId: 'toonarchive-c3859',
    authDomain: 'toonarchive-c3859.firebaseapp.com',
    storageBucket: 'toonarchive-c3859.firebasestorage.app',
    measurementId: 'G-Z2WDHTV85F',
  );
}
